<?php

include_once('ons_common.php');
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-22 at 19:18:19.
 */
class backup_restoreTest extends PHPUnit_Framework_TestCase {

    /**
     * @var backup_restore
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new backup_restore("localhost","phpunit","phpunit" ,"phpunit" );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers backup_restore::backup
     * @todo   Implement testBackup().
     */
    public function testBackup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers backup_restore::restore
     * @todo   Implement testRestore().
     */
    public function testRestore() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
